// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1xOdBUTFL03mdec6IJRSdlLuqe_nVXt0',
    appId: '1:693426662358:web:1620b5e2cb4b28aa499277',
    messagingSenderId: '693426662358',
    projectId: 'iti5-56046',
    authDomain: 'iti5-56046.firebaseapp.com',
    storageBucket: 'iti5-56046.firebasestorage.app',
    measurementId: 'G-XH0N3XRVHG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5VNyFQc4xu7waZtC1CESVSfa-7xY8Q50',
    appId: '1:693426662358:android:7c24e9a24146625e499277',
    messagingSenderId: '693426662358',
    projectId: 'iti5-56046',
    storageBucket: 'iti5-56046.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3OoEeMd3AdT4Lf_91eHtNbFjUn_m8eGc',
    appId: '1:693426662358:ios:a2cc8b453f0f66f5499277',
    messagingSenderId: '693426662358',
    projectId: 'iti5-56046',
    storageBucket: 'iti5-56046.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3OoEeMd3AdT4Lf_91eHtNbFjUn_m8eGc',
    appId: '1:693426662358:ios:a2cc8b453f0f66f5499277',
    messagingSenderId: '693426662358',
    projectId: 'iti5-56046',
    storageBucket: 'iti5-56046.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1xOdBUTFL03mdec6IJRSdlLuqe_nVXt0',
    appId: '1:693426662358:web:075080427bdbcf14499277',
    messagingSenderId: '693426662358',
    projectId: 'iti5-56046',
    authDomain: 'iti5-56046.firebaseapp.com',
    storageBucket: 'iti5-56046.firebasestorage.app',
    measurementId: 'G-JV3PBB7DFT',
  );
}
